Add(cli): secret-mv command
mps-gmbh/vault-toolbox pull request #1
Opened 2019-12-10 15:21 UTC by alexarcoss

2019-12-10 15:32 UTC, JanoschDeurer requested changes

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        print("Original From Path:", from_path)
```suggestion

```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        print("Original To Path:", to_path)
```suggestion
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        to_path: path to move the folders
```suggestion
        :to_path: path to move the folders
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +            logging.info("Reading the secret: %s", address)
```suggestion
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        secret_details = {}
```suggestion
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +            secret_details[version] = response.json()["data"]["data"]
```suggestion
            data = response.json()["data"]["data"]
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +            data = secret_details[version]
```suggestion
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        logging.info("Reading the secret: %s", address)
```suggestion
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        return new_list
```suggestion
        return response.json()["data"]["versions"].keys()
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        new_list = secret_details.keys()
```suggestion
```

2019-12-10 15:32 UTC, JanoschDeurer commented on vault/secret.py
> +        secret_details = response.json()["data"]["versions"]
```suggestion
```

2020-01-10 12:59 UTC, JanoschDeurer requested changes

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/group.py
> +Author: Janosch Deurer
```suggestion
Author: Alex Arcos
```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/group.py
> +Mail: deurer@mps-med.de
```suggestion
Mail: arcos@mps-med.de
```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/group.py
> +    """Class for wrapping the acl policies part of the vault api."""
```suggestion
    """Class for wrapping the group part of the vault api."""
```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/group.py
> +        """ List all policies
```suggestion
        """ List all groups
```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/group.py
> +        :returns: list of all policies
```suggestion
        :returns: list of all groups
```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/group.py
> +        # Actually run vault
```suggestion

```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/policy.py
> +Author: Janosch Deurer
```suggestion
Author: Tobias Malkmus
```

2020-01-10 12:59 UTC, JanoschDeurer commented on vault/policy.py
> +Mail: deurer@mps-med.de
```suggestion
Mail: malkmus@mps-med.de
```

2020-01-10 13:16 UTC, JanoschDeurer requested changes

2020-01-10 13:16 UTC, JanoschDeurer commented on vault_toolbox.py
> +    print(str(args))
```suggestion
```

2020-01-14 10:37 UTC, MalkmusT approved these changes

2020-01-14 10:38 UTC, merged